# -*- coding: utf-8 -*-
'''
Created on 5 cze 2014

@author: Katarzyna Krasnowska
'''

import re

def get_advp_sem_obls(advp):
    print advp
    adv = re.match(ur'advp\((.*)\)', advp).group(1)
    if adv in adv_sem_obls:
        return adv_sem_obls[adv]
    else:
        return set(['OBL-ADV', 'OBL-MOD'])

adv_sem_obls = {
# z Walentego
u'blisko' : set(['OBL-ADL', 'OBL-LOCAT']),
u'ciągle' : set(['OBL-DUR']),
u'często' : set(['OBL-TEMP']),
u'częstokroć' : set(['OBL-TEMP']),
u'daleko' : set(['OBL-ADL', 'OBL-LOCAT']),
u'dawno' : set(['OBL-TEMP']),
u'dokoła' : set(['OBL-LOCAT']),
u'dokąd' : set(['OBL-ADL']),
u'dokądkolwiek' : set(['OBL-ADL']),
u'donikąd' : set(['OBL-ADL']),
u'dookoła' : set(['OBL-LOCAT']),
u'dotychczas' : set(['OBL-TEMP']),
u'dotąd' : set(['OBL-TEMP']),
u'drzewiej' : set(['OBL-TEMP']),
u'dzisiaj' : set(['OBL-TEMP']),
u'dziś' : set(['OBL-TEMP']),
u'długo' : set(['OBL-DUR']),
u'gdzie' : set(['OBL-LOCAT']),
u'gdziekolwiek' : set(['OBL-LOCAT']),
u'gdzieniegdzie' : set(['OBL-LOCAT']),
u'gdzieś' : set(['OBL-LOCAT']),
u'gdzież' : set(['OBL-LOCAT']),
u'ile' : set(['OBL-DUR']),
u'ilekolwiek' : set(['OBL-DUR']),
u'jeszcze' : set(['OBL-DUR']),
u'jutro' : set(['OBL-TEMP']),
u'już' : set(['OBL-DUR']),
u'kiedy' : set(['OBL-TEMP']),
u'kiedykolwiek' : set(['OBL-TEMP']),
u'kiedyś' : set(['OBL-TEMP']),
u'krótko' : set(['OBL-DUR']),
u'którędy' : set(['OBL-PERL']),
u'którędykolwiek' : set(['OBL-PERL']),
u'którędyś' : set(['OBL-PERL']),
u'którędyż' : set(['OBL-PERL']),
u'kędy' : set(['OBL-PERL']),
u'kędykolwiek' : set(['OBL-PERL']),
u'latoś' : set(['OBL-TEMP']),
u'nadal' : set(['OBL-DUR']),
u'naokoło' : set(['OBL-LOCAT']),
u'naokół' : set(['OBL-LOCAT']),
u'naonczas' : set(['OBL-TEMP']),
u'natenczas' : set(['OBL-TEMP']),
u'naówczas' : set(['OBL-TEMP']),
u'nieczęsto' : set(['OBL-TEMP']),
u'niedaleko' : set(['OBL-ADL', 'OBL-LOCAT']),
u'niedawno' : set(['OBL-TEMP']),
u'niedługo' : set(['OBL-TEMP']),
u'niegdyś' : set(['OBL-TEMP']),
u'niekiedy' : set(['OBL-TEMP']),
u'nieopodal' : set(['OBL-LOCAT']),
u'nieraz' : set(['OBL-TEMP']),
u'nierzadko' : set(['OBL-TEMP']),
u'nigdzie' : set(['OBL-LOCAT']),
u'nikędy' : set(['OBL-TEMP']),
u'ninie' : set(['OBL-TEMP']),
u'nisko' : set(['OBL-LOCAT']),
u'obecnie' : set(['OBL-TEMP']),
u'obok' : set(['OBL-LOCAT']),
u'onegdaj' : set(['OBL-TEMP']),
u'ongi' : set(['OBL-TEMP']),
u'ongiś' : set(['OBL-TEMP']),
u'opodal' : set(['OBL-LOCAT']),
u'owędy' : set(['OBL-PERL']),
u'podówczas' : set(['OBL-TEMP']),
u'pojutrze' : set(['OBL-TEMP']),
u'poniżej' : set(['OBL-LOCAT']),
u'popojutrze' : set(['OBL-TEMP']),
u'potem' : set(['OBL-TEMP']),
u'powyżej' : set(['OBL-LOCAT']),
u'przedwczoraj' : set(['OBL-TEMP']),
u'przenigdy' : set(['OBL-TEMP']),
u'późno' : set(['OBL-TEMP']),
u'rzadko' : set(['OBL-TEMP']),
u'skąd' : set(['OBL-ABL']),
u'skądciś' : set(['OBL-ABL']),
u'skądinąd' : set(['OBL-ABL']),
u'skądkolwiek' : set(['OBL-ABL']),
u'skądsiś' : set(['OBL-ABL']),
u'skądś' : set(['OBL-ABL']),
u'skądże' : set(['OBL-ABL']),
u'sporadycznie' : set(['OBL-TEMP']),
u'stamtąd' : set(['OBL-ABL']),
u'stąd' : set(['OBL-ABL']),
u'tam' : set(['OBL-ADL', 'OBL-LOCAT']),
u'tamtędy' : set(['OBL-PERL']),
u'tamże' : set(['OBL-ADL', 'OBL-LOCAT']),
u'teraz' : set(['OBL-TEMP']),
u'trochę' : set(['OBL-DUR']),
u'tu' : set(['OBL-ADL', 'OBL-LOCAT']),
u'tutaj' : set(['OBL-ADL', 'OBL-LOCAT']),
u'tyle' : set(['OBL-DUR']),
u'tędy' : set(['OBL-PERL']),
u'wciąż' : set(['OBL-DUR']),
u'wczas' : set(['OBL-TEMP']),
u'wcześnie' : set(['OBL-TEMP']),
u'wczoraj' : set(['OBL-TEMP']),
u'wewnątrz' : set(['OBL-LOCAT']),
u'wkoło' : set(['OBL-LOCAT']),
u'wkrótce' : set(['OBL-TEMP']),
u'wnet' : set(['OBL-TEMP']),
u'wokoło' : set(['OBL-LOCAT']),
u'wokół' : set(['OBL-LOCAT']),
u'wonczas' : set(['OBL-TEMP']),
u'wstecz' : set(['OBL-ADL']),
u'wszędy' : set(['OBL-LOCAT']),
u'wszędzie' : set(['OBL-LOCAT']),
u'wtedy' : set(['OBL-TEMP']),
u'wtenczas' : set(['OBL-TEMP']),
u'wysoko' : set(['OBL-LOCAT']),
u'wówczas' : set(['OBL-TEMP']),
u'zaraz' : set(['OBL-TEMP']),
u'zawsze' : set(['OBL-TEMP']),
u'zewsząd' : set(['OBL-ABL']),
u'znikąd' : set(['OBL-ABL']),
u'ówcześnie' : set(['OBL-TEMP']),
u'ówdzie' : set(['OBL-LOCAT']),
}